import lookOne from "@/assets/toma-look-1.jpg";
import lookTwo from "@/assets/toma-look-2.jpg";
import lookThree from "@/assets/toma-look-3.jpg";

export type Category = "Shirts" | "Pants" | "Shoes" | "Bags";

export type Product = {
  id: number;
  name: string;
  category: Category;
  material: string;
  color: string;
  price: number;
  image: string;
  hoverImage: string;
  description: string;
  sizes: string[];
  lowStock?: string;
  specs: {
    composition: string;
    fit: string;
    finishing: string;
    care: string;
    provenance: string;
  };
};

export const products: Product[] = [
  {
    id: 1,
    name: "Porto Linen Shirt",
    category: "Shirts",
    material: "Linen",
    color: "Oatmeal",
    price: 465,
    image: lookOne,
    hoverImage: lookThree,
    description: "An airy spread-collar shirt cut for an easy Mediterranean drape.",
    sizes: ["S", "M", "L", "XL"],
    lowStock: "Only 2 left in M",
    specs: {
      composition: "100% European linen, garment-washed for softness.",
      fit: "Relaxed Italian drape. Model is 188 cm and wears size M.",
      finishing: "Australian mother-of-pearl buttons and hand-finished side gussets.",
      care: "Cold hand wash or gentle professional dry clean. Hang dry.",
      provenance: "Crafted in Italy by a family-owned workshop near Perugia.",
    },
  },
  {
    id: 2,
    name: "Arezzo Cashmere Polo",
    category: "Shirts",
    material: "Cashmere",
    color: "Taupe",
    price: 895,
    image: lookOne,
    hoverImage: lookThree,
    description: "A fine-gauge knit polo with a softly structured open collar.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    specs: {
      composition: "100% Mongolian cashmere, 18-gauge two-ply knit.",
      fit: "Refined regular fit. Model is 188 cm and wears size M.",
      finishing: "Fully fashioned seams, ribbed cuffs, genuine horn buttons.",
      care: "Professional dry clean. Fold and store with cedar.",
      provenance: "Spun and knitted in Umbria, Italy.",
    },
  },
  {
    id: 3,
    name: "Orvieto Poplin Overshirt",
    category: "Shirts",
    material: "Cotton",
    color: "Ivory",
    price: 590,
    image: lookThree,
    hoverImage: lookOne,
    description: "A light outer layer balancing shirt precision with jacket ease.",
    sizes: ["S", "M", "L", "XL"],
    specs: {
      composition: "100% long-staple Egyptian cotton poplin.",
      fit: "Straight, relaxed silhouette. Model is 188 cm and wears size M.",
      finishing: "Horn buttons, twin needle seams, hand-stitched pick detailing.",
      care: "Machine wash cold on delicate cycle. Air dry and press gently.",
      provenance: "Cut and finished in Veneto, Italy.",
    },
  },
  {
    id: 4,
    name: "Ravello Silk Henley",
    category: "Shirts",
    material: "Silk",
    color: "Soft Slate",
    price: 680,
    image: lookThree,
    hoverImage: lookOne,
    description: "A supple long-sleeve layer with quiet luster and natural breathability.",
    sizes: ["S", "M", "L", "XL"],
    specs: {
      composition: "70% linen / 30% Mulberry silk jersey.",
      fit: "Close through the shoulder with an easy body. Model wears M.",
      finishing: "Mother-of-pearl placket buttons and hand-bound neckline.",
      care: "Cold hand wash with silk detergent. Dry flat away from sunlight.",
      provenance: "Knitted and assembled in Como, Italy.",
    },
  },
  {
    id: 5,
    name: "Assisi Pleated Trouser",
    category: "Pants",
    material: "Linen",
    color: "Warm Sand",
    price: 720,
    image: lookOne,
    hoverImage: lookThree,
    description: "Double-pleated tailoring with a fluid break and relaxed waist.",
    sizes: ["30", "32", "34", "36", "38"],
    lowStock: "Only 1 left in 32",
    specs: {
      composition: "58% linen / 42% virgin wool woven in Biella.",
      fit: "Relaxed rise and tailored taper. Model is 188 cm and wears 32.",
      finishing: "Extended waistband, genuine horn closure, hand-finished hems.",
      care: "Professional dry clean only. Steam between wears.",
      provenance: "Tailored in an artisanal workshop in Tuscany, Italy.",
    },
  },
  {
    id: 6,
    name: "Matera Drawstring Chino",
    category: "Pants",
    material: "Cotton",
    color: "Oatmeal",
    price: 545,
    image: lookThree,
    hoverImage: lookOne,
    description: "Brushed cotton comfort resolved with an elegant tailored line.",
    sizes: ["30", "32", "34", "36", "38"],
    specs: {
      composition: "97% brushed cotton / 3% elastane.",
      fit: "Mid-rise with a soft taper. Model is 188 cm and wears 32.",
      finishing: "Internal drawstring, horn button and tonal pick stitching.",
      care: "Cold machine wash inside out. Line dry.",
      provenance: "Crafted in Italy from Italian-milled cotton.",
    },
  },
  {
    id: 7,
    name: "Biella Flannel Trouser",
    category: "Pants",
    material: "Wool",
    color: "Charcoal",
    price: 765,
    image: lookThree,
    hoverImage: lookOne,
    description: "Impeccably soft flannel tailoring for unhurried winter days.",
    sizes: ["30", "32", "34", "36"],
    specs: {
      composition: "100% Super 130s virgin wool flannel.",
      fit: "Tailored taper with a single pleat. Model is 188 cm and wears 32.",
      finishing: "Cupro lining, horn closure and hand-sewn bar tacks.",
      care: "Professional dry clean only. Rest between wears.",
      provenance: "Cloth woven in Biella and tailored in Tuscany, Italy.",
    },
  },
  {
    id: 8,
    name: "Parma Suede Loafer",
    category: "Shoes",
    material: "Leather/Suede",
    color: "Espresso",
    price: 790,
    image: lookTwo,
    hoverImage: lookOne,
    description: "An unlined penny loafer formed for glove-like comfort.",
    sizes: ["40", "41", "42", "43", "44", "45"],
    lowStock: "Only 2 left in 43",
    specs: {
      composition: "Full-grain calfskin suede with vegetable-tanned leather lining.",
      fit: "True to European size with a softly structured almond toe.",
      finishing: "Hand-stitched apron, Blake construction, natural leather sole.",
      care: "Brush after wear; protect with a neutral suede spray.",
      provenance: "Handmade in a family-owned workshop in Parma, Italy.",
    },
  },
  {
    id: 9,
    name: "Roma Court Sneaker",
    category: "Shoes",
    material: "Leather/Suede",
    color: "Ivory",
    price: 650,
    image: lookTwo,
    hoverImage: lookThree,
    description: "A clean court silhouette pared back to its most essential form.",
    sizes: ["40", "41", "42", "43", "44", "45"],
    specs: {
      composition: "Full-grain calfskin with calf leather lining.",
      fit: "True to size with a generous, softly padded forefoot.",
      finishing: "Hand-burnished edges and lightweight Vibram rubber sole.",
      care: "Wipe with a soft damp cloth and condition monthly.",
      provenance: "Made by specialist sneaker artisans in Marche, Italy.",
    },
  },
  {
    id: 10,
    name: "Torino Chelsea Boot",
    category: "Shoes",
    material: "Leather/Suede",
    color: "Charcoal",
    price: 980,
    image: lookTwo,
    hoverImage: lookThree,
    description: "A softly sculpted boot built with enduring welted construction.",
    sizes: ["40", "41", "42", "43", "44", "45"],
    specs: {
      composition: "Soft-grain French calfskin with full leather lining.",
      fit: "True to size with a refined round toe and close ankle.",
      finishing: "Goodyear welt, tonal elastic gussets and Vibram rubber sole.",
      care: "Condition with neutral cream and rest with cedar shoe trees.",
      provenance: "Bench-made in Montegranaro, Italy.",
    },
  },
  {
    id: 11,
    name: "Firenze Weekender",
    category: "Bags",
    material: "Leather/Suede",
    color: "Espresso",
    price: 1890,
    image: lookTwo,
    hoverImage: lookOne,
    description: "A capacious travel companion designed to acquire a rich patina.",
    sizes: ["One Size"],
    specs: {
      composition: "Full-grain Italian calfskin with cotton-canvas lining.",
      fit: "48 × 30 × 23 cm; cabin compatible with detachable shoulder strap.",
      finishing: "Solid brass Raccagni zip, hand-painted edges, protective feet.",
      care: "Wipe clean and condition quarterly with neutral leather balm.",
      provenance: "Cut and assembled by leather artisans in Florence, Italy.",
    },
  },
  {
    id: 12,
    name: "Siena Suede Tote",
    category: "Bags",
    material: "Leather/Suede",
    color: "Taupe",
    price: 1260,
    image: lookTwo,
    hoverImage: lookThree,
    description: "An unstructured everyday tote in exceptionally soft suede.",
    sizes: ["One Size"],
    specs: {
      composition: "Full-grain calfskin suede with nappa leather base.",
      fit: "40 × 35 × 14 cm with comfortable shoulder-length handles.",
      finishing: "Magnetic closure, suede-lined pocket and hand-bound handles.",
      care: "Brush gently and protect from rain. Specialist clean only.",
      provenance: "Handcrafted in a small Tuscan leather workshop.",
    },
  },
  {
    id: 13,
    name: "Milano Messenger",
    category: "Bags",
    material: "Leather/Suede",
    color: "Charcoal",
    price: 1190,
    image: lookTwo,
    hoverImage: lookThree,
    description: "A discreet crossbody with room for the day’s essentials.",
    sizes: ["One Size"],
    specs: {
      composition: "Pebbled full-grain calfskin with cotton-twill lining.",
      fit: "28 × 22 × 8 cm with adjustable leather shoulder strap.",
      finishing: "Raccagni zip, palladium hardware and hand-painted edges.",
      care: "Wipe clean and nourish with a neutral leather conditioner.",
      provenance: "Handcrafted in Florence, Italy.",
    },
  },
  {
    id: 14,
    name: "Bologna Document Folio",
    category: "Bags",
    material: "Leather/Suede",
    color: "Warm Sand",
    price: 740,
    image: lookTwo,
    hoverImage: lookOne,
    description: "A slim, precise folio for documents and a 13-inch notebook.",
    sizes: ["One Size"],
    specs: {
      composition: "Vegetable-tanned full-grain calfskin with suede lining.",
      fit: "35 × 25 × 3 cm; accommodates most 13-inch laptops.",
      finishing: "Raccagni zip, saddle stitching and burnished edges.",
      care: "Condition sparingly and avoid prolonged moisture.",
      provenance: "Made in Bologna by a third-generation leather atelier.",
    },
  },
];